export const BLOCK_WIDTH : number = 32;
export const NUM_BLOCKS : number = 15;
export const PIXEL_WIDTH : number = BLOCK_WIDTH * NUM_BLOCKS;
export const PIXEL_HEIGHT : number = 300; // canvas size, not max ball neight (it goes a bit out the top ...)
export const CEILING_CLEARANCE : number = 20; // ball can go up to height - this (if ball is bigger than this it will go a bit out the top)
export const FLOOR_CLEARANCE : number = 40;
export const POST_WIDTH : number = BLOCK_WIDTH / 2;
export const MIN_COLLECT_HEIGHT : number = 40;
export const HIT_WIDTH_SIZE : number = 34;
export const BALL_SIZE : number = 24;
export const HORIZONTAL_STEP_PIXELS : number = 4;
export const BONUS_LIFE : number = 2;
export const VERTICAL_MOVE_SIZE : number = 7;
export const BONUS_SPAWN_CHANCE : number = 0.57;
export const ROUNDS : number = 10;